config/routes.rb
WenBlogV1::Application.routes.draw do
  resources :wen_users

  resources :sessions, only: [:new, :create, :destroy]

  get "home_pages/home"
  root "home_pages#home"

  match "/signup", to: 'wen_users#new', via: 'get'
  match "/signin", to: 'sessions#new', via: 'get'
  match "/signout", to: 'sessions#destroy', via: 'delete'

  

  

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 30 }, uniqueness: true

  validates :tel, numericality: { only_integer: true}

  validates :addr, presence: true, length: { maximum: 100 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  
  has_secure_password
  validates :password, length: { in: 6..20 }
  
end

app/models/wen_user.rb
class WenUser < ActiveRecord::Base
  before_save { self.name }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 30 }, uniqueness: true

  validates :tel, numericality: { only_integer: true}

  validates :addr, presence: true, length: { maximum: 100 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  
  has_secure_password
  validates :password, length: { in: 6..20 }

  def WenUser.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def WenUser.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
    def create_remember_token
      self.remember_token = WenUser.encrypt(WenUser.new_remember_token)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    wen_user = WenUser.find_by(name: params[:session][:name])
    if wen_user && wen_user.authenticate(params[:session][:password])
      sign_in wen_user
      redirect_back_or wen_user
    else
      flash.now[:error] = 'Invalid name/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/controllers/wen_users_controller.rb
class WenUsersController < ApplicationController
  before_action :set_wen_user, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  # GET /wen_users
  # GET /wen_users.json
  def index
    @wen_users = WenUser.all
  end

  # GET /wen_users/1
  # GET /wen_users/1.json
  def show
  end

  # GET /wen_users/new
  def new
    @wen_user = WenUser.new
  end

  # GET /wen_users/1/edit
  def edit
  end

  # POST /wen_users
  # POST /wen_users.json
  def create
    @wen_user = WenUser.new(wen_user_params)

    respond_to do |format|
      if @wen_user.save
        sign_in @wen_user
        format.html { redirect_to @wen_user, notice: 'Wen user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wen_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @wen_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wen_users/1
  # PATCH/PUT /wen_users/1.json
  def update
    respond_to do |format|
      if @wen_user.update(wen_user_params)
        format.html { redirect_to @wen_user, notice: 'Wen user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wen_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wen_users/1
  # DELETE /wen_users/1.json
  def destroy
    @wen_user.destroy
    respond_to do |format|
      format.html { redirect_to wen_users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wen_user
      @wen_user = WenUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wen_user_params
      params.require(:wen_user).permit(:name, :email, :tel, :addr, :password, :password_confirmation)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @wen_user = WenUser.find(params[:id])
      redirect_to(root_url) unless current_user?(@wen_user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in( wen_user )
    remember_token = WenUser.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    wen_user.update_attribute(:remember_token, WenUser.encrypt(remember_token))
    self.current_user = wen_user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = WenUser.encrypt(cookies[:remember_token])
    @current_user ||= WenUser.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wen_users_helper.rb
module WenUsersHelper
   # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(wen_user)
    gravatar_id = Digest::MD5::hexdigest(wen_user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: wen_user.name, class: "gravatar")
  end
end

app/views/home_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>HomePages#home</h1>
  <p>Find me in app/views/home_pages/home.html.erb</p>

  <%= link_to "Sign up now!", '/signup', class: "btn btn-large btn-primary"  %>
</div>

<%= link_to image_tag("smile.jpg", alt: "cat"), '#' %>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
  <div class = "navbar-inner">
    <div class = "container">
      <%= link_to "Function", '#', id:"logo" %>
      <nav>
        <ul class = "nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Square", "#" %></li>
          <% if signed_in? %>
            <li><%= link_to "WenUsers", wen_users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Blog", current_user %></li>
                <li><%= link_to "Settings", edit_wen_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if it IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WenBlog | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= flash[:error] %>
    <%= flash[:notice] %>
  <%= render 'layouts/header' %>
  <div class = "container">
    
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Users' Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/wen_users/_form.html.erb
<div class="row">
  <div class="span6 offset3">
	<%= form_for(@wen_user) do |f| %>
	  <% if @wen_user.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@wen_user.errors.count, "error") %> prohibited this wen_user from being saved:</h2>

		  <ul>
		  <% @wen_user.errors.full_messages.each do |msg| %>
		    <li><%= msg %></li>
		  <% end %>
		  </ul>
		</div>
	  <% end %>

	  <div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	  </div>
	  <div class="field">
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	  </div>
	  <div class="field">
		<%= f.label :tel %><br>
		<%= f.number_field :tel %>
	  </div>
	  <div class="field">
		<%= f.label :addr %><br>
		<%= f.text_field :addr %>
	  </div>
	  <div class="field">
		<%= f.label :password %><br>
		<%= f.text_field :password %>
	  </div>
	  <div class="field">
		<%= f.label :password_confirmation %><br>
		<%= f.text_field :password_confirmation %>
	  </div>
	  <div class="actions">
		<%= f.submit "Submit", class: "btn btn-large btn-primary" %>
	  </div>
	<% end %>
  </div>
</div>

app/views/wen_users/edit.html.erb
<h1>Editing wen_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @wen_user %> |
<%= link_to 'Back', wen_users_path %>

app/views/wen_users/index.html.erb
<h1>Listing wen_users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Tel</th>
      <th>Addr</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @wen_users.each do |wen_user| %>
      <tr>
        <td><%= wen_user.name %></td>
        <td><%= wen_user.email %></td>
        <td><%= wen_user.tel %></td>
        <td><%= wen_user.addr %></td>
        <td><%= link_to 'Show', wen_user %></td>
        <td><%= link_to 'Edit', edit_wen_user_path(wen_user) %></td>
        <td><%= link_to 'Destroy', wen_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wen user', new_wen_user_path %>

app/views/wen_users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>New wen_user sign up</h1>

<%= render 'form' %>

<%= link_to 'Back', wen_users_path %>

app/views/wen_users/show.html.erb
<% provide(:title, @wen_user.name) %>

<div class="row">
  <aside class="span4">
    <section>
	<p id="notice"><%= notice %></p>
	<p>
	  <%= gravatar_for @wen_user %>
	  <strong>Name:</strong>
	  <%= @wen_user.name %>
	</p>
    </section>
  </aside>
</div>

<p>
  <strong>Email:</strong>
  <%= @wen_user.email %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @wen_user.tel %>
</p>

<p>
  <strong>Addr:</strong>
  <%= @wen_user.addr %>
</p>



<%= link_to 'Edit', edit_wen_user_path(@wen_user) %> |
<%= link_to 'Back', wen_users_path %>